name: Convert questionnaires and extract
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Prepare
        run: mkdir ./extract
      - name: Build bundle
        run: docker compose run --rm build-seeds
      - name: Extract questionnaires
        run: bun extract.js
      - name: Switch to compiled
        uses: actions/checkout@v4
        with:
          ref: compiled
      - name: Prepare commit
        run: rm -rf bundle && mv extract bundle
      - name: commit-push_branch-test
        uses: dsayling/commit-branch-check-action@v0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update questionnaires"
          dest-branch: compiled

